apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  backendName: tbc-ontap-nas
  svm: ekssvm
  aws:
    fsxFilesystemID: fs-0425716071ec34eab
  credentials:
    #name: "trident-secret"
    #name: arn:aws:secretsmanager:ap-northeast-2:446805103418:secret:fsxn_password_secret-vJqXMy
    type: awsarn
    name: "arn:aws:secretsmanager:ap-northeast-2:446805103418:secret:satreci_fsx_pass_secret-augrKX"
