apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-07T01:59:14Z"
  finalizers:
  - trident.netapp.io
  generation: 1
  name: tridentactionmirrorupdates.trident.netapp.io
  resourceVersion: "1620"
  uid: f1290454-4ff3-46ea-a2a1-4a0bebd70933
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-external
    kind: TridentActionMirrorUpdate
    listKind: TridentActionMirrorUpdateList
    plural: tridentactionmirrorupdates
    shortNames:
    - tamu
    - tamupdate
    - tamirrorupdate
    singular: tridentactionmirrorupdate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Namespace
      jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - description: State
      jsonPath: .status.state
      name: State
      type: string
    - description: CompletionTime
      jsonPath: .status.completionTime
      name: CompletionTime
      type: date
    - description: Message
      jsonPath: .status.message
      name: Message
      priority: 1
      type: string
    - description: LocalVolumeHandle
      jsonPath: .status.localVolumeHandle
      name: LocalVolumeHandle
      priority: 1
      type: string
    - description: RemoteVolumeHandle
      jsonPath: .status.remoteVolumeHandle
      name: RemoteVolumeHandle
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - trident
    - trident-external
    kind: TridentActionMirrorUpdate
"/var/folders/d7/2t7hgr492r19s2ls3d6f8py80000gn/T/kubectl1.30.0-edit-3218114275.yaml" 93L, 2455B
    - trident-external
    kind: TridentActionMirrorUpdate
    listKind: TridentActionMirrorUpdateList
    plural: tridentactionmirrorupdates
    shortNames:
    - tamu
    - tamupdate
    - tamirrorupdate
    singular: tridentactionmirrorupdate
  conditions:
  - lastTransitionTime: "2025-02-07T01:59:14Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-02-07T01:59:14Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1