apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:25Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentactionsnapshotrestores.trident.netapp.io
  resourceVersion: "1559"
  uid: dbcc90ea-9386-4b45-82f2-c9e76ade10e4
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-external
    kind: TridentActionSnapshotRestore
    listKind: TridentActionSnapshotRestoreList
    plural: tridentactionsnapshotrestores
    shortNames:
      - tasr
    singular: tridentactionsnapshotrestore
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Namespace
          jsonPath: .metadata.namespace
          name: Namespace
          type: string
        - description: PVC
          jsonPath: .spec.pvcName
          name: PVC
          type: string
        - description: Snapshot
          jsonPath: .spec.volumeSnapshotName
          name: Snapshot
          type: string
        - description: State
          jsonPath: .status.state
          name: State
          type: string
        - description: CompletionTime
          jsonPath: .status.completionTime
          name: CompletionTime
          type: date
        - description: Message
          jsonPath: .status.message
          name: Message
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-external
    kind: TridentActionSnapshotRestore
    listKind: TridentActionSnapshotRestoreList
    plural: tridentactionsnapshotrestores
    shortNames:
      - tasr
    singular: tridentactionsnapshotrestore
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:25Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:25Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
