apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:20Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentbackendconfigs.trident.netapp.io
  resourceVersion: "1561"
  uid: 824d8982-6ba7-4bfb-a318-c620602921f4
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
      - trident-external
    kind: TridentBackendConfig
    listKind: TridentBackendConfigList
    plural: tridentbackendconfigs
    shortNames:
      - tbc
      - tbconfig
      - tbackendconfig
    singular: tridentbackendconfig
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The backend name
          jsonPath: .status.backendInfo.backendName
          name: Backend Name
          type: string
        - description: The backend UUID
          jsonPath: .status.backendInfo.backendUUID
          name: Backend UUID
          type: string
        - description: The backend config phase
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The result of the last operation
          jsonPath: .status.lastOperationStatus
          name: Status
          type: string
        - description: The storage driver type
          jsonPath: .spec.storageDriverName
          name: Storage Driver
          priority: 1
          type: string
        - description: The deletion policy
          jsonPath: .status.deletionPolicy
          name: Deletion Policy
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
      - trident-external
    kind: TridentBackendConfig
    listKind: TridentBackendConfigList
    plural: tridentbackendconfigs
    shortNames:
      - tbc
      - tbconfig
      - tbackendconfig
    singular: tridentbackendconfig
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:20Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:20Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
