apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:19Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentbackends.trident.netapp.io
  resourceVersion: "1560"
  uid: 054611bd-bd46-4ed3-94e9-bbfa4f66ee1a
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentBackend
    listKind: TridentBackendList
    plural: tridentbackends
    shortNames:
      - tbe
      - tbackend
    singular: tridentbackend
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The backend name
          jsonPath: .backendName
          name: Backend
          type: string
        - description: The backend UUID
          jsonPath: .backendUUID
          name: Backend UUID
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
    kind: TridentBackend
    listKind: TridentBackendList
    plural: tridentbackends
    shortNames:
      - tbe
      - tbackend
    singular: tridentbackend
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:19Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:19Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
