apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:19Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentsnapshotinfos.trident.netapp.io
  resourceVersion: "1565"
  uid: d3a89b22-cdc4-43de-b543-0133f37dea4c
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
      - trident-external
    kind: TridentSnapshotInfo
    listKind: TridentSnapshotInfoList
    plural: tridentsnapshotinfos
    shortNames:
      - tsi
      - tsinfo
      - tsnapshotinfo
    singular: tridentsnapshotinfo
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: VolumeSnapshotContent Handle
          jsonPath: .status.snapshotHandle
          name: Snapshot Handle
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                snapshotName:
                  type: string
              required:
                - snapshotName
              type: object
            status:
              properties:
                lastTransitionTime:
                  type: string
                observedGeneration:
                  type: integer
                snapshotHandle:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
      - trident-external
    kind: TridentSnapshotInfo
    listKind: TridentSnapshotInfoList
    plural: tridentsnapshotinfos
    shortNames:
      - tsi
      - tsinfo
      - tsnapshotinfo
    singular: tridentsnapshotinfo
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:19Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:19Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
