apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:23Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentsnapshots.trident.netapp.io
  resourceVersion: "1564"
  uid: 224dab5e-9c2c-4d7c-9cea-4ed08b9a0cc0
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentSnapshot
    listKind: TridentSnapshotList
    plural: tridentsnapshots
    shortNames:
      - tss
      - tsnap
      - tsnapshot
    singular: tridentsnapshot
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The snapshot's state
          jsonPath: .state
          name: State
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
    kind: TridentSnapshot
    listKind: TridentSnapshotList
    plural: tridentsnapshots
    shortNames:
      - tss
      - tsnap
      - tsnapshot
    singular: tridentsnapshot
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:23Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:23Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
