apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:21Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentstorageclasses.trident.netapp.io
  resourceVersion: "1569"
  uid: df99166e-eebe-4e25-b92e-6d2b0b3d5adc
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentStorageClass
    listKind: TridentStorageClassList
    plural: tridentstorageclasses
    shortNames:
      - tsc
      - tstorageclass
    singular: tridentstorageclass
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
    kind: TridentStorageClass
    listKind: TridentStorageClassList
    plural: tridentstorageclasses
    shortNames:
      - tsc
      - tstorageclass
    singular: tridentstorageclass
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:21Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:21Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
