apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:18Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentversions.trident.netapp.io
  resourceVersion: "1571"
  uid: 57a1f17f-f300-4230-a5f7-4f218ed8dabb
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentVersion
    listKind: TridentVersionList
    plural: tridentversions
    shortNames:
      - tver
      - tversion
    singular: tridentversion
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The Trident version
          jsonPath: .trident_version
          name: Version
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
    kind: TridentVersion
    listKind: TridentVersionList
    plural: tridentversions
    shortNames:
      - tver
      - tversion
    singular: tridentversion
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:18Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:18Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
