apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:22Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentvolumepublications.trident.netapp.io
  resourceVersion: "1578"
  uid: 8c557f70-6618-47d0-912b-c4ccaf298e78
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentVolumePublication
    listKind: TridentVolumePublicationList
    plural: tridentvolumepublications
    shortNames:
      - tvp
      - tvpub
      - tvpublication
      - tvolpub
      - tvolumepub
      - tvolpublication
      - tvolumepublication
    singular: tridentvolumepublication
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Volume ID
          jsonPath: .volumeID
          name: Volume
          type: string
        - description: Node ID
          jsonPath: .nodeID
          name: Node
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            accessMode:
              format: int32
              type: integer
            nodeID:
              type: string
            readOnly:
              type: boolean
            volumeID:
              type: string
          required:
            - volumeID
            - nodeID
            - readOnly
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-internal
    kind: TridentVolumePublication
    listKind: TridentVolumePublicationList
    plural: tridentvolumepublications
    shortNames:
      - tvp
      - tvpub
      - tvpublication
      - tvolpub
      - tvolumepub
      - tvolpublication
      - tvolumepublication
    singular: tridentvolumepublication
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:22Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:22Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
