apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-02-06T03:31:24Z"
  finalizers:
    - trident.netapp.io
  generation: 1
  name: tridentvolumereferences.trident.netapp.io
  resourceVersion: "1575"
  uid: 6a826c86-9307-46ad-842a-8a16965a75e0
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-external
      - trident-internal
    kind: TridentVolumeReference
    listKind: TridentVolumeReferenceList
    plural: tridentvolumereferences
    shortNames:
      - tvr
      - tvref
    singular: tridentvolumereference
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                pvcName:
                  type: string
                pvcNamespace:
                  type: string
              required:
                - pvcName
                - pvcNamespace
              type: object
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - trident
      - trident-external
      - trident-internal
    kind: TridentVolumeReference
    listKind: TridentVolumeReferenceList
    plural: tridentvolumereferences
    shortNames:
      - tvr
      - tvref
    singular: tridentvolumereference
  conditions:
    - lastTransitionTime: "2025-02-06T03:31:24Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2025-02-06T03:31:24Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1
