apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: tridentbackends.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentBackend
    listKind: TridentBackendList
    plural: tridentbackends
    shortNames:
      - tbe
      - tbackend
    singular: tridentbackend
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The backend name
          jsonPath: .backendName
          name: Backend
          type: string
        - description: The backend UUID
          jsonPath: .backendUUID
          name: Backend UUID
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
