apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: tridentstorageclasses.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentStorageClass
    listKind: TridentStorageClassList
    plural: tridentstorageclasses
    shortNames:
      - tsc
      - tstorageclass
    singular: tridentstorageclass
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
