apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: tridenttransactions.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident-internal
    kind: TridentTransaction
    listKind: TridentTransactionList
    plural: tridenttransactions
    shortNames:
      - ttx
      - ttransaction
    singular: tridenttransaction
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
