apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: tridentversions.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentVersion
    listKind: TridentVersionList
    plural: tridentversions
    shortNames:
      - tver
      - tversion
    singular: tridentversion
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The Trident version
          jsonPath: .trident_version
          name: Version
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
