apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: tridentvolumes.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
      - trident
      - trident-internal
    kind: TridentVolume
    listKind: TridentVolumeList
    plural: tridentvolumes
    shortNames:
      - tvol
      - tvolume
    singular: tridentvolume
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - description: The volume's size
          jsonPath: .config.size
          name: Size
          priority: 1
          type: string
        - description: The volume's storage class
          jsonPath: .config.storageClass
          name: Storage Class
          priority: 1
          type: string
        - description: The volume's state
          jsonPath: .state
          name: State
          priority: 1
          type: string
        - description: The volume's protocol
          jsonPath: .config.protocol
          name: Protocol
          priority: 1
          type: string
        - description: The volume's backend UUID
          jsonPath: .backendUUID
          name: Backend UUID
          priority: 1
          type: string
        - description: The volume's pool
          jsonPath: .pool
          name: Pool
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
